variables:
  GIT_SUBMODULE_STRATEGY: recursive
  JAVA_VERSION: "25"
  SENTRY_RELEASE: "$CI_COMMIT_SHA"

stages:
  - test
  - build

.build:
  stage: build
  when: manual
  allow_failure: false
  tags:
    - runner-8
  script:
    - 'docker build $DOCKER_BUILD_ARGS --no-cache -f $COMPONENT/docker/$DOCKERFILE -t eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA -t eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:latest .'
    - 'docker push eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA'
    - 'docker push eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:latest'
  variables:
    DOCKERFILE: Dockerfile
    DOCKER_BUILD_ARGS: ""

.buildWeb:
  stage: build
  when: manual
  allow_failure: false
  tags:
    - runner-8
  script:
    - 'docker build --secret id=sentry-auth-token,env=SENTRY_AUTH_TOKEN --secret id=mui-license-key,env=VITE_MUI_LICENCE_KEY --build-arg VITE_SENTRY_DSN --build-arg SENTRY_URL --build-arg SENTRY_ENVIRONMENT --no-cache -f $COMPONENT/docker/$DOCKERFILE -t eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA -t eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:latest .'
    - 'docker push eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA'
    - 'docker push eu.gcr.io/inqool-1301/permonik/test/$COMPONENT_NAME:latest'
  variables:
    DOCKERFILE: Dockerfile
    SENTRY_ENVIRONMENT: test

.buildProd:
  stage: build
  when: manual
  allow_failure: false
  tags:
    - runner-8
  script:
    - 'docker build $DOCKER_BUILD_ARGS --no-cache -f $COMPONENT/docker/$DOCKERFILE -t eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA -t eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:latest .'
    - 'docker push eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA'
    - 'docker push eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:latest'
  variables:
    DOCKERFILE: Dockerfile
    DOCKER_BUILD_ARGS: ""

.buildWebProd:
  stage: build
  when: manual
  allow_failure: false
  tags:
    - runner-8
  script:
    - 'docker build --secret id=sentry-auth-token,env=SENTRY_AUTH_TOKEN --secret id=mui-license-key,env=VITE_MUI_LICENCE_KEY --build-arg VITE_SENTRY_DSN --build-arg SENTRY_URL --build-arg SENTRY_ENVIRONMENT --no-cache -f $COMPONENT/docker/$DOCKERFILE -t eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA -t eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:latest .'
    - 'docker push eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:$CI_COMMIT_SHORT_SHA'
    - 'docker push eu.gcr.io/inqool-1301/permonik/prod/$COMPONENT_NAME:latest'
  variables:
    DOCKERFILE: Dockerfile
    SENTRY_ENVIRONMENT: production


test_permonik_api:
  stage: test
  allow_failure: false
  tags:
    - runner-8
  rules:
    - if: '$CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "prod"'
      when: manual
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-$JAVA_VERSION-openjdk-amd64
    - export PATH="$JAVA_HOME/bin:$PATH"
    - java --version
    - ./gradlew :permonik-api:test
  artifacts:
    when: always
    reports:
      junit: permonik-api/build/test-results/test/*.xml
    paths:
      - permonik-api/build/reports/tests/
    expire_in: 7 days

build_permonik_api_test:
  extends: .build
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: manual
  variables:
    COMPONENT: permonik-api
    COMPONENT_NAME: permonik-api
    DOCKER_BUILD_ARGS: "--secret id=sentry-auth-token,env=SENTRY_AUTH_TOKEN --build-arg SENTRY_DSN --build-arg SENTRY_ENVIRONMENT --build-arg SENTRY_RELEASE --build-arg SENTRY_URL"
    SENTRY_ENVIRONMENT: test

build_permonik_gateway_test:
  extends: .build
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: manual
  variables:
    COMPONENT: permonik-gateway
    COMPONENT_NAME: permonik-gateway

build_permonik_web_admin_test:
  extends: .buildWeb
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: manual
  variables:
    COMPONENT: permonik-web
    DOCKERFILE: admin/Dockerfile
    COMPONENT_NAME: permonik-web-admin

build_permonik_web_public_test:
  extends: .buildWeb
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: manual
  variables:
    COMPONENT: permonik-web
    DOCKERFILE: public/Dockerfile
    COMPONENT_NAME: permonik-web-public

### PROD SECTION

build_permonik_api_prod:
  extends: .buildProd
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
  variables:
    COMPONENT: permonik-api
    COMPONENT_NAME: permonik-api
    DOCKER_BUILD_ARGS: "--secret id=sentry-auth-token,env=SENTRY_AUTH_TOKEN --build-arg SENTRY_DSN --build-arg SENTRY_ENVIRONMENT --build-arg SENTRY_RELEASE --build-arg SENTRY_URL"
    SENTRY_ENVIRONMENT: production

build_permonik_gateway_prod:
  extends: .buildProd
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
  variables:
    COMPONENT: permonik-gateway
    COMPONENT_NAME: permonik-gateway

build_permonik_web_admin_prod:
  extends: .buildWebProd
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
  variables:
    COMPONENT: permonik-web
    DOCKERFILE: admin/Dockerfile
    COMPONENT_NAME: permonik-web-admin

build_permonik_web_public_prod:
  extends: .buildWebProd
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
  variables:
    COMPONENT: permonik-web
    DOCKERFILE: public/Dockerfile
    COMPONENT_NAME: permonik-web-public
