services:
  permonik-api:
    image: eu.gcr.io/inqool-1301/permonik/test/permonik-api:${PERMONIK_TAG}
    depends_on:
      - permonik-database
      - permonik-redis
    build:
      context: .
      dockerfile: permonik-api/docker/Dockerfile
    networks:
      - permonik
    expose:
      - 8080
    deploy:
      resources:
        reservations:
          memory: '1024M'
        limits:
          memory: '2048M'
    environment:
      SPRING_PROFILES_ACTIVE: test
      REDIS_HOST: permonik-redis
      TZ: "Europe/Prague"
      SERVER_PORT: "8080"

  permonik-web-admin:
    image: eu.gcr.io/inqool-1301/permonik/test/permonik-web-admin:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-web/docker/admin/Dockerfile
    networks:
      - permonik
    expose:
      - 8080
    deploy:
      resources:
        reservations:
          memory: '12M'
        limits:
          memory: '24M'

  permonik-web-public:
    image: eu.gcr.io/inqool-1301/permonik/test/permonik-web-public:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-web/docker/public/Dockerfile
    networks:
      - permonik
    expose:
      - 8080
    deploy:
      resources:
        reservations:
          memory: '12M'
        limits:
          memory: '24M'

  permonik-gateway:
    image: eu.gcr.io/inqool-1301/permonik/test/permonik-gateway:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-gateway/Dockerfile
    networks:
      - permonik
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          memory: '96M'
        limits:
          memory: '192M'
    volumes:
      - /opt/shibboleth-sp-config:/etc/shibboleth:ro
      - /var/log/supervisor:/var/log/supervisor
      - /var/log/apache2:/var/log/apache2
      - /var/log/shibboleth:/var/log/shibboleth

  permonik-database:
    image: solr:9.9.0
    networks:
      - permonik
    ports:
      - "8983:8983"
    deploy:
      resources:
        reservations:
          memory: '3072M'
        limits:
          memory: '4096M'
    environment:
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
      SOLR_MODULES: analysis-extras
    volumes:
      - /data/solr:/var/solr

  permonik-redis:
    image: redis:8-alpine
    networks:
      - permonik
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100m
    volumes:
      - redis-volume:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  permonik:

volumes:
  redis-volume:
