services:
  permonik-api:
    image: eu.gcr.io/inqool-1301/permonik/permonik-api:${PERMONIK_TAG}
    depends_on:
      - permonik-database
    build:
      context: .
      dockerfile: permonik-api/docker/Dockerfile
    networks:
      - permonik
    ports:
      - "8081:8080"
    deploy:
      resources:
        reservations:
          memory: '1024M'
        limits:
          memory: '2048M'
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xverify:none -Xms1024m -Xmx1500m"
      TZ: "Europe/Prague"
      SERVER_PORT: "8080"

  permonik-web-admin:
    image: eu.gcr.io/inqool-1301/permonik/permonik-web-admin:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-web/docker/public/admin.Dockerfile
    networks:
      - permonik
    ports:
      - "8082:8080"
    deploy:
      resources:
        reservations:
          memory: '12M'
        limits:
          memory: '24M'

  permonik-web-public:
    image: eu.gcr.io/inqool-1301/permonik/permonik-web-public:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-web/docker/public/public.Dockerfile
    networks:
      - permonik
    ports:
      - "8083:8080"
    deploy:
      resources:
        reservations:
          memory: '12M'
        limits:
          memory: '24M'

  permonik-gateway:
    image: eu.gcr.io/inqool-1301/permonik/permonik-gateway:${PERMONIK_TAG}
    depends_on:
      - permonik-shibboleth-sp
    build:
      context: .
      dockerfile: permonik-gateway/Dockerfile
    networks:
      - permonik
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          memory: '12M'
        limits:
          memory: '24M'

  permonik-database:
    image: solr:9.7.0
    networks:
      - permonik
    ports:
      - "8983:8983"
    environment:
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
    volumes:
      - solr-data:/var/solr
      - ./permonik-database/cores:/opt/solr/server/solr/mycores:ro
      - ./permonik-database/init-cores.sh:/docker-entrypoint-initdb.d/init-cores.sh:ro

  permonik-shibboleth-sp:
    image: eu.gcr.io/inqool-1301/permonik/permonik-shibboleth-sp:${PERMONIK_TAG}
    build:
      context: .
      dockerfile: permonik-shibboleth-sp/Dockerfile
    ports:
      - "8084:80"
    volumes:
      - /opt/shibboleth-sp-config/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro
      - /opt/shibboleth-sp-config/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro
      - /opt/shibboleth-sp-config/metadata-template.xml:/etc/shibboleth/metadata-template.xml:ro
      - /opt/shibboleth-sp-config/sp-cert.pem:/etc/shibboleth/sp-cert.pem:ro
      - /opt/shibboleth-sp-config/sp-key.pem:/etc/shibboleth/sp-key.pem:ro
      - /var/log/shibboleth:/var/log/shibboleth
    networks:
      - permonik

volumes:
  solr-data:

networks:
  permonik:
