services:
  permonik-api:
    depends_on:
      - permonik-database
      - permonik-redis
    build:
      context: .
      dockerfile: permonik-api/docker/Dockerfile
    networks:
      - permonik
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: '1024M'
    environment:
      SOLR_URL: http://permonik-database:8983/solr
      REDIS_HOST: permonik-redis
      SPRING_PROFILES_ACTIVE: dev
      TZ: "Europe/Prague"

  permonik-database:
    image: solr:9.10.0
    networks:
      - permonik
    ports:
      - "8983:8983"
    deploy:
      resources:
        limits:
          memory: '2048M'
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
      SOLR_MODULES: analysis-extras
    volumes:
      - ./solr-data:/var/solr

  permonik-redis:
    image: redis:8-alpine
    networks:
      - permonik
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100m
    volumes:
      - redis-volume:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  permonik:

volumes:
  redis-volume:
