spring:
  config:
    activate:
      on-profile: test
  threads:
    virtual:
      enabled: true
  web:
    error:
      path: /error
      whitelabel:
        enabled: true
      include-exception: true
      include-message: always

solr:
  host: http://permonik-database:8983/solr

permonik:
  security:
    internal-jwt:
      secret: ${IDENTITY_JWT_SECRET}

server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  file:
    name: "permonik-api.log"

sentry:
  dsn: ${SENTRY_DSN:}
  enabled: true
  send-default-pii: false
  environment: ${SENTRY_ENVIRONMENT:}
  release: ${SENTRY_RELEASE:}
