spring:
  config:
    activate:
      on-profile: test
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  web:
    error:
      path: /error
      whitelabel:
        enabled: true
      include-exception: true
      include-message: always

solr:
  host: http://permonik-database:8983/solr

server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  servlet:
    session:
      cookie:
        path: /
        name: "SESSION"
        secure: true
        http-only: true
        same-site: strict
      timeout: 480m

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  file:
    name: "permonik-api.log"

sentry:
  dsn: ${SENTRY_DSN:}
  enabled: true
  send-default-pii: false
  environment: ${SENTRY_ENVIRONMENT:}
  release: ${SENTRY_RELEASE:}
