spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  web:
    error:
      path: /error
      whitelabel:
        enabled: true
      include-exception: true
      include-message: always

#sentry:
#  dsn: ${SENTRY_DSN}
#  send-default-pii: true
#  exception-resolver-order: -2147483647

solr:
  host: ${SOLR_URL:http://localhost:8983/solr}

permonik:
  security:
    internal-jwt:
      secret: ${IDENTITY_JWT_SECRET}

server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
#logging:
#  level:
#    org:
#      springframework:
#        security: "DEBUG"

sentry:
  dsn: ""
  enabled: false
