services:
  # used for precreating new solr version
  permonik-database-precreate:
    image: solr:9.9.0
    ports:
      - "8991:8983"
    command:
      - solr-precreate
      - gettingstarted

  # used for reindexing new solr version
  permonik-database-new:
    image: solr:9.9.0
    ports:
      - "8990:8983"
    environment:
      - SOLR_MODULES=analysis-extras
    volumes:
      - ./new-solr-data:/var/solr


volumes:
  new-solr-data:
